-- Jarod Miller (jcm138)

insert into USER_ROLE values(1,'Organizer');
insert into USER_ROLE values(2,'Coach');
insert into USER_ROLE values(3,'Guest');
insert into USER_ACCOUNT(username,passkey,role_id,last_login) values('gianna_angelopovlos','Athens',1,TO_DATE('2004-08-29','yyyy-mm-dd'));
insert into USER_ACCOUNT(username,passkey,role_id,last_login) values('hu_jintao','Beijing',1,TO_DATE('2008-08-24','yyyy-mm-dd'));
insert into USER_ACCOUNT(username,passkey,role_id,last_login) values('sebastian_newbold','London',1,TO_DATE('2012-08-12','yyyy-mm-dd'));
insert into USER_ACCOUNT(username,passkey,role_id,last_login) values('carlos_aurthur','Rio',1,TO_DATE('2016-08-21','yyyy-mm-dd'));
insert into USER_ACCOUNT(username,passkey,role_id,last_login) values('guest_account','GUEST',3,TO_DATE('2020-01-20','yyyy-mm-dd'));
insert into MEDAL values (1,'gold',10);
insert into MEDAL values (2,'silver',5);
insert into MEDAL values (3,'bronze',4);
commit;
insert into OLYMPICS(olympic_num, host_city, opening_date, closing_date, official_website) values (28,'Athens',TO_DATE('2004-08-13','yyyy-mm-dd'),TO_DATE('2004-08-29','yyyy-mm-dd'),'https://www.olympic.org/athens-2004');
insert into OLYMPICS(olympic_num, host_city, opening_date, closing_date, official_website) values (29,'Beijing',TO_DATE('2008-08-08','yyyy-mm-dd'),TO_DATE('2008-08-24','yyyy-mm-dd'),'https://www.olympic.org/beijing-2008');
insert into OLYMPICS(olympic_num, host_city, opening_date, closing_date, official_website) values (30,'London',TO_DATE('2012-07-27','yyyy-mm-dd'),TO_DATE('2012-08-12','yyyy-mm-dd'),'https://www.olympic.org/london-2012');
insert into OLYMPICS(olympic_num, host_city, opening_date, closing_date, official_website) values (31,'Rio',TO_DATE('2016-08-05','yyyy-mm-dd'),TO_DATE('2016-08-21','yyyy-mm-dd'),'https://www.olympic.org/rio-2016');
insert into SPORT(sport_name, description, dob, team_size) values ('5000M','12.5 laps around the track',TO_DATE('1912-07-10','yyyy-mm-dd'),1);
insert into SPORT(sport_name, description, dob, team_size) values ('Singles Table Tennis','ping pong',TO_DATE('1988-10-01','yyyy-mm-dd'),1);
insert into SPORT(sport_name, description, dob, team_size) values ('Individual 70M Archery','bow and arrow',TO_DATE('1972-09-10','yyyy-mm-dd'),1);
insert into SPORT(sport_name, description, dob, team_size) values ('Beach Volleyball','pairs',TO_DATE('1996-07-27','yyyy-mm-dd'),2);
insert into SPORT(sport_name, description, dob, team_size) values ('Doubles Badminton','plongggg',TO_DATE('1992-08-04','yyyy-mm-dd'),2);
insert into SPORT(sport_name, description, dob, team_size) values ('Coxless Four Rowing','paddle paddle',TO_DATE('1996-07-27','yyyy-mm-dd'),4);
insert into COUNTRY(country, country_code) values ('Great Britain','GBR');
insert into COUNTRY(country, country_code) values ('United States','USA');
insert into COUNTRY(country, country_code) values ('Ethiopia','ETH');
insert into COUNTRY(country, country_code) values ('China','CHN');
insert into COUNTRY(country, country_code) values ('Japan','JPN');
insert into COUNTRY(country, country_code) values ('Germany','DEU');
insert into COUNTRY(country, country_code) values ('Brazil','BRA');
insert into COUNTRY(country, country_code) values ('Malaysia','MYS');
insert into COUNTRY(country, country_code) values ('Australia','AUS');
insert into COUNTRY(country, country_code) values ('Italy','ITA');
insert into COUNTRY(country, country_code) values ('Kenya','KEN');
insert into COUNTRY(country, country_code) values ('Mexico','MEX');
insert into COUNTRY(country, country_code) values ('Denmark','DNK');
insert into COUNTRY(country, country_code) values ('Indonesia','IDN');
insert into COUNTRY(country, country_code) values ('France','FRA');
insert into COUNTRY(country, country_code) values ('Morocco','MAR');
insert into COUNTRY(country, country_code) values ('Canada','CAN');
insert into COUNTRY(country, country_code) values ('Bahrain','BHR');
insert into COUNTRY(country, country_code) values ('Uganda','UGA');
insert into COUNTRY(country, country_code) values ('Eritrea','ERI');
insert into COUNTRY(country, country_code) values ('South Africa','ZAF');
insert into COUNTRY(country, country_code) values ('Peru','PER');
insert into COUNTRY(country, country_code) values ('Taiwan','TPE');
insert into COUNTRY(country, country_code) values ('North Korea','PRK');
insert into COUNTRY(country, country_code) values ('South Korea','KOR');
insert into COUNTRY(country, country_code) values ('New Zealand','NZL');
insert into COUNTRY(country, country_code) values ('Poland','POL');
insert into COUNTRY(country, country_code) values ('Netherlands','NLD');
insert into COUNTRY(country, country_code) values ('Algeria','DZA');
insert into COUNTRY(country, country_code) values ('Spain','ESP');
insert into COUNTRY(country, country_code) values ('Djibouti','DJI');
insert into COUNTRY(country, country_code) values ('Sweden','SWE');
insert into COUNTRY(country, country_code) values ('Ukraine','UKR');
insert into COUNTRY(country, country_code) values ('Belarus','BLR');
insert into COUNTRY(country, country_code) values ('Slovenia','SVN');
insert into COUNTRY(country, country_code) values ('Czech Republic','CZE');
insert into COUNTRY(country, country_code) values ('Greece','GRC');
insert into COUNTRY(country, country_code) values ('Russia','RUS');
insert into VENUE(olympic_id, venue_name, capacity) values (1,'Athens Olympic Stadium',1);
insert into VENUE(olympic_id, venue_name, capacity) values (1,'Galatsi Olympic Hall',2);
insert into VENUE(olympic_id, venue_name, capacity) values (1,'Panathinaiko Stadium',3);
insert into VENUE(olympic_id, venue_name, capacity) values (1,'Olympic Volleyball Centre',2);
insert into VENUE(olympic_id, venue_name, capacity) values (1,'Goudi Olympic Hall',2);
insert into VENUE(olympic_id, venue_name, capacity) values (1,'Schinias Olympic Rowing Centre',4);
insert into VENUE(olympic_id, venue_name, capacity) values (2,'Beijing National Stadium',2);
insert into VENUE(olympic_id, venue_name, capacity) values (2,'Peking University Gymnasium',1);
insert into VENUE(olympic_id, venue_name, capacity) values (2,'Olympic Green Archery Field',2);
insert into VENUE(olympic_id, venue_name, capacity) values (2,'Beach Volleyball Ground',2);
insert into VENUE(olympic_id, venue_name, capacity) values (2,'Beijing Gymnasium',3);
insert into VENUE(olympic_id, venue_name, capacity) values (2,'Shunyi Rowing-Canoeing Park',4);
insert into VENUE(olympic_id, venue_name, capacity) values (3,'Olympic Stadium',3);
insert into VENUE(olympic_id, venue_name, capacity) values (3,'ExCeL London',3);
insert into VENUE(olympic_id, venue_name, capacity) values (3,'Lords Cricket Ground',2);
insert into VENUE(olympic_id, venue_name, capacity) values (3,'Womens Beach Volleyball',3);
insert into VENUE(olympic_id, venue_name, capacity) values (3,'Wembley Arena',4);
insert into VENUE(olympic_id, venue_name, capacity) values (3,'Eton Dorney',2);
insert into VENUE(olympic_id, venue_name, capacity) values (4,'Olympic Stadium',1);
insert into VENUE(olympic_id, venue_name, capacity) values (4,'Riocentro',4);
insert into VENUE(olympic_id, venue_name, capacity) values (4,'Sambadrome Marques de Sapucai',3);
insert into VENUE(olympic_id, venue_name, capacity) values (4,'Copacabana Stadium',3);
insert into VENUE(olympic_id, venue_name, capacity) values (4,'Rodrigo de Freitas Lagoon',2);
commit;
-- now that we have olympics, sports, countries, and venues in the db, we can create events
insert into EVENT(sport_id, venue_id, gender, event_time) values (1,1,1,TO_DATE('2004-08-20','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (1,7,1,TO_DATE('2008-08-20','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (1,13,1,TO_DATE('2012-08-08','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (1,19,1,TO_DATE('2016-08-18','yyyy-mm-dd'));

insert into EVENT(sport_id, venue_id, gender, event_time) values (2,2,1,TO_DATE('2004-08-20','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (2,8,1,TO_DATE('2008-08-20','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (2,14,1,TO_DATE('2012-08-08','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (2,20,1,TO_DATE('2016-08-18','yyyy-mm-dd'));

insert into EVENT(sport_id, venue_id, gender, event_time) values (3,3,2,TO_DATE('2004-08-20','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (3,9,2,TO_DATE('2008-08-20','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (3,15,2,TO_DATE('2012-08-08','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (3,21,2,TO_DATE('2016-08-18','yyyy-mm-dd'));

insert into EVENT(sport_id, venue_id, gender, event_time) values (4,4,2,TO_DATE('2004-08-20','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (4,10,2,TO_DATE('2008-08-20','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (4,16,2,TO_DATE('2012-08-08','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (4,22,2,TO_DATE('2016-08-18','yyyy-mm-dd'));

insert into EVENT(sport_id, venue_id, gender, event_time) values (5,5,1,TO_DATE('2004-08-20','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (5,11,1,TO_DATE('2008-08-20','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (5,17,1,TO_DATE('2012-08-08','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (5,20,1,TO_DATE('2016-08-18','yyyy-mm-dd'));

insert into EVENT(sport_id, venue_id, gender, event_time) values (6,6,1,TO_DATE('2004-08-20','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (6,12,1,TO_DATE('2008-08-20','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (6,18,1,TO_DATE('2012-08-08','yyyy-mm-dd'));
insert into EVENT(sport_id, venue_id, gender, event_time) values (6,23,1,TO_DATE('2016-08-18','yyyy-mm-dd'));
commit;
/*
5000M
Singles Table Tennis
Individual 70 Metres Archery
Beach Volleyball
Doubles Badminton
Coxless Four Rowing
*/
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','Morocco',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('Hicham','El Guerrouj','Moroccan','Berkane, Morocco',TO_DATE('1974-09-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','Ethiopia',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('Kenenisa','Bekele','Ethiopian','Bekoji, Ethiopia',TO_DATE('1982-06-13','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','Kenya',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('Eliud','Kipchoge','Kenyan','Nandi County, Kenya',TO_DATE('1984-11-05','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','Ethiopia',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('Gebregziabher','Gebremariam','Ethiopian','Tigray, Ethiopia',TO_DATE('1984-09-10','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,4);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','Ethiopia',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('Dejene','Berhanu','Ethiopian','Addis Alem, Ethiopia',TO_DATE('1980-12-12','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,5);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','Kenya',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('John','Kibowen','Kenyan','Changach, Kenya',TO_DATE('1969-04-21','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,6);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','Eritrea',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('Zersenay','Tadese','Eritrean','Adi Bana,Eritrea',TO_DATE('1982-02-08','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,7);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','Australia',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('Craig','Mottram','Australian','Frankston, Australia',TO_DATE('1980-06-18','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,8);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','Morocco',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('Hicham','Bellani','Moroccan','unknown, Morocco',TO_DATE('1979-09-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,9);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','Algeria',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('Ali','Saidi Sief','Algerian','Constantine, Algeria',TO_DATE('1978-03-18','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,10);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','United States',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('Tim','Broe','American','Peoria, Illinois',TO_DATE('1977-06-20','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,11);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','South Africa',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('Alistair','Ian Cragg','Irish-South African','Johannesburg, South Africa',TO_DATE('1980-06-13','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,12);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','Morocco',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('Abderrahim','Goumri','Moroccan','Temara, Morocco',TO_DATE('1976-05-21','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,13);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'5000M','Algeria',null,coach_no);
registerTeam(team_no,1);
curr_athlete := addParticipant('Samir','Moussaoui','Algerian','Bordj Bou-Azzeridj, Algeria',TO_DATE('1975-05-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),1,curr_athlete,14);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','Ethiopia',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('Kenenisa','Bekele','Ethiopian','Bekoji, Ethiopia',TO_DATE('1982-06-13','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','Kenya',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('Eliud','Kipchoge','Kenyan','Nandi County, Kenya',TO_DATE('1984-11-05','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','Kenya',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('Edwin','Cheruiyot Soi','Kenyan','Kericho, Kenya',TO_DATE('1986-03-03','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','Uganda',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('Moses','Ndiema Kipsiro','Ugandan','Singare, Uganda',TO_DATE('1986-09-02','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,4);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','Ethiopia',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('Abreham','Cherkos','Ethiopian','unknown, Ethiopia',TO_DATE('1989-09-23','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,5);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','Ethiopia',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('Tariku','Bekele','Ethiopian','Bekoji, Ethiopia',TO_DATE('1987-02-28','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,6);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','Mexico',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('Juan','Luis Barrios','Mexican','Mexico City, Mexico',TO_DATE('1983-06-24','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,7);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','Kenya',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('James','Kwalia C''Kurui','Kenyan-Qataris','Trans Nzoia, Kenya',TO_DATE('1984-06-12','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,8);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','United States',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('Bernard','Lagat','Kenyan-American','Kapsabet, Kenya',TO_DATE('1974-12-12','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,9);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','Eritrea',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('Kidane','Tadasse','Eritrean','Adi Bana, Eritrea',TO_DATE('1987-01-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,10);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','Spain',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('Alemayehu','Bezabeh','Spanish-Ethiopian','Addis Ababa, Alemayehu',TO_DATE('1986-01-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,11);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','Kenya',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('Thomas','Pkemei Longosiwa','Kenyan','West Pokot District, Kenya',TO_DATE('1982-01-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,12);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','United States',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('Matthew','Tegenkamp','American','Lee''s Summit, Missouri',TO_DATE('1982-01-19','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,13);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'5000M','Spain',null,coach_no);
registerTeam(team_no,2);
curr_athlete := addParticipant('Jesus','Espana','Spanish','Valdemoro, Madrid',TO_DATE('1978-08-21','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),2,curr_athlete,14);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','Great Britain',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Mo','Farah','British','Mogadishu, Somalia',TO_DATE('1983-03-23','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','Ethiopia',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Dejen','Gebremeskel','Ethiopian','unknown, Ethiopia',TO_DATE('1989-11-24','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','Kenya',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Thomas','Pkemei Longosiwa','Kenyan','West Pokot District, Kenya',TO_DATE('1982-01-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','United States',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Bernard','Lagat','Kenyan-American','Kapsabet, Kenya',TO_DATE('1974-12-12','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,4);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','Kenya',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Isiah','Kiplangat','Kenyan','Koech, Kenya',TO_DATE('1993-12-19','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,5);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','Morocco',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Abdalaati','Iguider','Moroccan','Errachida, Morocco',TO_DATE('1987-03-25','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,6);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','United States',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Galen','Rupp','American','Portland, Oregon',TO_DATE('1986-05-08','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,7);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','Mexico',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Juan','Luis Barrios','Mexican','Mexico City, Mexico',TO_DATE('1983-06-24','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,8);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','Ethiopia',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Hayle','Ibrahimov','Azerbaijan','Mekele, Ethiopia',TO_DATE('1990-01-18','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,9);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','United States',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Lopez','Lomong','American','Kimotong, South Sudan',TO_DATE('1985-01-05','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,10);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','Ethiopia',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Hagos','Gebrhiwet','Ethiopian','Ts''a''ida Imba, Ethiopia',TO_DATE('1994-05-11','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,11);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','Ethiopia',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Yenew','Alamirew','Ethiopian','Tilili, Amhara',TO_DATE('1990-05-27','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,12);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','Djibouti',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Mumin','Gala','Djiboutian','Djibouti City, Djibouti',TO_DATE('1986-09-06','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,13);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','Canada',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Cameron','Levins','Canadian','Black Creek, British Columbia',TO_DATE('1989-03-28','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,14);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'5000M','Uganda',null,coach_no);
registerTeam(team_no,3);
curr_athlete := addParticipant('Moses','Ndiema Kipsiro','Ugandan','Singare, Uganda',TO_DATE('1986-09-02','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),3,curr_athlete,15);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','Great Britain',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Mo','Farah','British','Mogadishu, Somalia',TO_DATE('1983-03-23','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','United States',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Paul','Kipkemoi Chelimo','Kenyan-American','Iten, Kenya',TO_DATE('1990-10-27','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','Ethiopia',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Hagos','Gebrhiwet','Ethiopian','Ts''a''ida Imba, Ethiopia',TO_DATE('1994-05-11','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','Canada',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Mohammed','Ahmed','Canadian','Mogadishu, Somalia',TO_DATE('1991-01-05','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,4);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','United States',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Bernard','Lagat','Kenyan-American','Kapsabet, Kenya',TO_DATE('1974-12-12','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,5);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','Great Britain',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Andrew','Butchart','British','Dunblane, Scotland',TO_DATE('1991-10-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,6);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','Bahrain',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Albert','Kibichii Rop','Bahrain','unknown, Bahrain',TO_DATE('1992-07-17','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,7);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','Uganda',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Joshua','Kiprui Cheptegei','Ugandan','Kapsewui, Uganda',TO_DATE('1996-09-12','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,8);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','Bahrain',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Birhanu','Balew','Bahrain','unknown, Ethiopia',TO_DATE('1996-02-27','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,9);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','Eritrea',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Abrar','Osman','Eritrean','unknown, Eritrea',TO_DATE('1994-01-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,10);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','United States',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Hassan','Mead','Somali-American','unknown, Somalia',TO_DATE('1989-06-28','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,11);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','Ethiopia',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Dejen','Gebremeskel','Ethiopian','unknown, Ethiopia',TO_DATE('1989-11-24','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,12);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','South Africa',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Elroy','Gelant','South African','unknown, South Africa',TO_DATE('1986-08-25','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,13);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','Australia',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('Brett','Robinson','Australian','Canberra, Australia',TO_DATE('1991-05-08','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,14);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'5000M','Peru',null,coach_no);
registerTeam(team_no,4);
curr_athlete := addParticipant('David','Torrence','Peruvian-American','Okinawa, Japan',TO_DATE('1985-11-26','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),4,curr_athlete,15);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Singles Table Tennis','South Korea',null,coach_no);
registerTeam(team_no,5);
curr_athlete := addParticipant('Ryu','Seung-Min','Korean','Seoul, South Korea',TO_DATE('1982-08-05','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),5,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Singles Table Tennis','China',null,coach_no);
registerTeam(team_no,5);
curr_athlete := addParticipant('Wang','Hao','Chinese','Changchun, China',TO_DATE('1983-12-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),5,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Singles Table Tennis','China',null,coach_no);
registerTeam(team_no,5);
curr_athlete := addParticipant('Wang','Liqin','Chinese','Shanghai, China',TO_DATE('1978-06-18','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),5,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Singles Table Tennis','Sweden',null,coach_no);
registerTeam(team_no,5);
curr_athlete := addParticipant('Jan-Ove','Waldner','Swedish','Stockholm, Sweden',TO_DATE('1965-10-03','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),5,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Singles Table Tennis','China',null,coach_no);
registerTeam(team_no,6);
curr_athlete := addParticipant('Ma','Lin','Chinese','Shenyang, China',TO_DATE('1980-02-19','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),6,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Singles Table Tennis','China',null,coach_no);
registerTeam(team_no,6);
curr_athlete := addParticipant('Wang','Hao','Chinese','Changchun, China',TO_DATE('1983-12-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),6,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Singles Table Tennis','China',null,coach_no);
registerTeam(team_no,6);
curr_athlete := addParticipant('Wang','Liqin','Chinese','Shanghai, China',TO_DATE('1978-06-18','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),6,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Singles Table Tennis','Sweden',null,coach_no);
registerTeam(team_no,6);
curr_athlete := addParticipant('Jorgen','Persson','Swedish','Halmstad, Sweden',TO_DATE('1966-04-22','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),6,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Singles Table Tennis','China',null,coach_no);
registerTeam(team_no,7);
curr_athlete := addParticipant('Zhang','Jike','Chinese','Qingdao, China',TO_DATE('1988-02-16','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),7,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Singles Table Tennis','China',null,coach_no);
registerTeam(team_no,7);
curr_athlete := addParticipant('Wang','Hao','Chinese','Changchun, China',TO_DATE('1983-12-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),7,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Singles Table Tennis','Ukraine',null,coach_no);
registerTeam(team_no,7);
curr_athlete := addParticipant('Dimitrij','Ovtcharov','German','Kiev, Ukrainian SSR',TO_DATE('1988-09-02','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),7,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Singles Table Tennis','Taiwan',null,coach_no);
registerTeam(team_no,7);
curr_athlete := addParticipant('Chuang','Chih-yuan','Taiwan','Kaohsiung, Taiwan',TO_DATE('1981-04-02','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),7,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Singles Table Tennis','China',null,coach_no);
registerTeam(team_no,8);
curr_athlete := addParticipant('Ma','Long','Chinese','Anshan, China',TO_DATE('1988-10-20','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),8,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Singles Table Tennis','China',null,coach_no);
registerTeam(team_no,8);
curr_athlete := addParticipant('Zhang','Jike','Chinese','Qingdao, China',TO_DATE('1988-02-16','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),8,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Singles Table Tennis','Japan',null,coach_no);
registerTeam(team_no,8);
curr_athlete := addParticipant('Jun','Mizutani','Japanese','Iwata, Japan',TO_DATE('1989-06-09','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),8,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Singles Table Tennis','Belarus',null,coach_no);
registerTeam(team_no,8);
curr_athlete := addParticipant('Vladimir','Samsonov','Belarus','Minsk, Belarus',TO_DATE('1976-04-17','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),8,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Individual 70M Archery','South Korea',null,coach_no);
registerTeam(team_no,9);
curr_athlete := addParticipant('Park','Sung-hyun','South Korean','Incheon, South Korea',TO_DATE('1983-01-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),9,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Individual 70M Archery','South Korea',null,coach_no);
registerTeam(team_no,9);
curr_athlete := addParticipant('Lee','Sung Jin','South Korean','unknown, Korea',TO_DATE('1985-03-07','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),9,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Individual 70M Archery','Great Britain',null,coach_no);
registerTeam(team_no,9);
curr_athlete := addParticipant('Alison','Williamson','British','Melton Mowbray, England',TO_DATE('1971-11-03','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),9,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Individual 70M Archery','Taiwan',null,coach_no);
registerTeam(team_no,9);
curr_athlete := addParticipant('Yuan','Shu-chi','Chinese','unknown, Taiwan',TO_DATE('1984-11-09','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),9,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Individual 70M Archery','China',null,coach_no);
registerTeam(team_no,10);
curr_athlete := addParticipant('Zhang','Juanjuan','Chinese','Qingdao, China',TO_DATE('1981-01-02','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),10,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Individual 70M Archery','South Korea',null,coach_no);
registerTeam(team_no,10);
curr_athlete := addParticipant('Park','Sung-hyun','South Korean','Incheon, South Korea',TO_DATE('1983-01-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),10,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Individual 70M Archery','South Korea',null,coach_no);
registerTeam(team_no,10);
curr_athlete := addParticipant('Yun','Ok-hee','South Korean','unknown, South Korea',TO_DATE('1985-03-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),10,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Individual 70M Archery','North Korea',null,coach_no);
registerTeam(team_no,10);
curr_athlete := addParticipant('Kwon','Un-Sil','North Korean','Hamhung, North Korea',TO_DATE('1983-09-17','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),10,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Individual 70M Archery','South Korea',null,coach_no);
registerTeam(team_no,11);
curr_athlete := addParticipant('Ki','Bo-Bae','South Korean','Anyang, South Korea',TO_DATE('1988-02-20','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),11,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Individual 70M Archery','Mexico',null,coach_no);
registerTeam(team_no,11);
curr_athlete := addParticipant('Aida','Roman','Mexican','Mexico City, Mexico',TO_DATE('1988-05-21','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),11,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Individual 70M Archery','Mexico',null,coach_no);
registerTeam(team_no,11);
curr_athlete := addParticipant('Mariana','Avitia','Mexican','Monterrey, Nuevo Leon',TO_DATE('1993-09-18','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),11,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Individual 70M Archery','United States',null,coach_no);
registerTeam(team_no,11);
curr_athlete := addParticipant('Khatuna','Lorig','Georgian-American','Tbilisi, Georgian SSR',TO_DATE('1974-01-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),11,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Individual 70M Archery','South Korea',null,coach_no);
registerTeam(team_no,12);
curr_athlete := addParticipant('Chang','Hye-jin','South Korean','unknown, South Korea',TO_DATE('1987-05-13','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),12,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Individual 70M Archery','Germany',null,coach_no);
registerTeam(team_no,12);
curr_athlete := addParticipant('Lisa','Unruh','German','unknown, Germany',TO_DATE('1988-04-12','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),12,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Individual 70M Archery','South Korea',null,coach_no);
registerTeam(team_no,12);
curr_athlete := addParticipant('Ki','Bo-Bae','South Korean','Anyang, South Korea',TO_DATE('1988-02-20','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),12,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Individual 70M Archery','Mexico',null,coach_no);
registerTeam(team_no,12);
curr_athlete := addParticipant('Alejandra','Valencia','Mexican','Hermosillo, Mexico',TO_DATE('1994-10-17','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),12,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Beach Volleyball','United States',null,coach_no);
registerTeam(team_no,13);
curr_athlete := addParticipant('Kerri','Walsh Jennings','American','Santa Clara, California',TO_DATE('1978-08-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),13,curr_athlete,1);
curr_athlete := addParticipant('Misty','May-Treanor','American','Los Angeles, California',TO_DATE('1977-07-30','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),13,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Beach Volleyball','Brazil',null,coach_no);
registerTeam(team_no,13);
curr_athlete := addParticipant('Shelda','Bede','Brazilian','Fortaleza, Brazil',TO_DATE('1973-01-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),13,curr_athlete,2);
curr_athlete := addParticipant('Adriana','Behar','Brazilian','Rio de Janeiro, Brazil',TO_DATE('1969-02-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),13,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Beach Volleyball','United States',null,coach_no);
registerTeam(team_no,13);
curr_athlete := addParticipant('Holly','McPeak','American','Manhattan Beach, California',TO_DATE('1969-05-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),13,curr_athlete,3);
curr_athlete := addParticipant('Elaine','Youngs','American','Orange, California',TO_DATE('1970-02-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),13,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Beach Volleyball','Australia',null,coach_no);
registerTeam(team_no,13);
curr_athlete := addParticipant('Natalie','Cook','Australian','Townsville, Queensland',TO_DATE('1975-01-19','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),13,curr_athlete,4);
curr_athlete := addParticipant('Nicole','Sanderson','Australian','Perth, Western Australia',TO_DATE('1976-04-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),13,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Beach Volleyball','United States',null,coach_no);
registerTeam(team_no,14);
curr_athlete := addParticipant('Kerri','Walsh Jennings','American','Santa Clara, California',TO_DATE('1978-08-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),14,curr_athlete,1);
curr_athlete := addParticipant('Misty','May-Treanor','American','Los Angeles, California',TO_DATE('1977-07-30','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),14,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Beach Volleyball','China',null,coach_no);
registerTeam(team_no,14);
curr_athlete := addParticipant('Tian','Jia','Chinese','Tianjin, China',TO_DATE('1981-02-09','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),14,curr_athlete,2);
curr_athlete := addParticipant('Wang','Jie','Chinese','Urumqi, China',TO_DATE('1983-12-04','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),14,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Beach Volleyball','China',null,coach_no);
registerTeam(team_no,14);
curr_athlete := addParticipant('Xue','Chen','Chinese','Fuzhou, China',TO_DATE('1989-02-18','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),14,curr_athlete,3);
curr_athlete := addParticipant('Zhang','Xi','Chinese','Jiangsu, China',TO_DATE('1985-04-19','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),14,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Beach Volleyball','Brazil',null,coach_no);
registerTeam(team_no,14);
curr_athlete := addParticipant('Talita','Antunes','Brazilian','Aquidauana, Brazil',TO_DATE('1982-08-29','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),14,curr_athlete,4);
curr_athlete := addParticipant('Renata','Ribeiro','Brazilian','Rio de Janeiro, Brazil',TO_DATE('1981-12-07','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),14,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Beach Volleyball','United States',null,coach_no);
registerTeam(team_no,15);
curr_athlete := addParticipant('Kerri','Walsh Jennings','American','Santa Clara, California',TO_DATE('1978-08-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),15,curr_athlete,1);
curr_athlete := addParticipant('Misty','May-Treanor','American','Los Angeles, California',TO_DATE('1977-07-30','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),15,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Beach Volleyball','United States',null,coach_no);
registerTeam(team_no,15);
curr_athlete := addParticipant('Jennifer','Kessy','American','San Clemente, California',TO_DATE('1977-07-31','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),15,curr_athlete,2);
curr_athlete := addParticipant('April','Ross','American','Costa Mesa, California',TO_DATE('1982-06-20','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),15,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Beach Volleyball','Brazil',null,coach_no);
registerTeam(team_no,15);
curr_athlete := addParticipant('Juliana','Silva','Brazilian','Santos, Brazil',TO_DATE('1983-07-22','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),15,curr_athlete,3);
curr_athlete := addParticipant('Larissa','Franca','Brazilian','Cachoeiro do Itapemirim, Brazil',TO_DATE('1982-04-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),15,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Beach Volleyball','China',null,coach_no);
registerTeam(team_no,15);
curr_athlete := addParticipant('Xue','Chen','Chinese','Fuzhou, China',TO_DATE('1989-02-18','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),15,curr_athlete,4);
curr_athlete := addParticipant('Zhang','Xi','Chinese','Jiangsu, China',TO_DATE('1985-04-19','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),15,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Beach Volleyball','Germany',null,coach_no);
registerTeam(team_no,16);
curr_athlete := addParticipant('Laura','Ludwig','German','Berlin, Germany',TO_DATE('1986-01-13','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),16,curr_athlete,1);
curr_athlete := addParticipant('Kira','Walkenhorst','German','Essen, Germany',TO_DATE('1990-11-18','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),16,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Beach Volleyball','Brazil',null,coach_no);
registerTeam(team_no,16);
curr_athlete := addParticipant('Agatha','Bednarczuk','Brazilian','Curitiba, Brazil',TO_DATE('1983-06-22','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),16,curr_athlete,2);
curr_athlete := addParticipant('Barbara','Seixas','Brazilian','Rio de Janeiro, Brazil',TO_DATE('1987-08-03','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),16,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Beach Volleyball','United States',null,coach_no);
registerTeam(team_no,16);
curr_athlete := addParticipant('Kerri','Walsh Jennings','American','Santa Clara, California',TO_DATE('1978-08-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),16,curr_athlete,3);
curr_athlete := addParticipant('April','Ross','American','Costa Mesa, California',TO_DATE('1982-06-20','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),16,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Beach Volleyball','Brazil',null,coach_no);
registerTeam(team_no,16);
curr_athlete := addParticipant('Larissa','Franca','Brazilian','Cachoeiro do Itapemirim, Brazil',TO_DATE('1982-04-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),16,curr_athlete,4);
curr_athlete := addParticipant('Talita','Antunes','Brazilian','Aquidauana, Brazil',TO_DATE('1982-08-29','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),16,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Doubles Badminton','South Korea',null,coach_no);
registerTeam(team_no,17);
curr_athlete := addParticipant('Kim','Dong-moon','South Korean','Gokseong, South Korea',TO_DATE('1975-09-22','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),17,curr_athlete,1);
curr_athlete := addParticipant('Ha','Tae-kwon','South Korean','Jeonju, South Korea',TO_DATE('1975-04-30','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),17,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Doubles Badminton','South Korea',null,coach_no);
registerTeam(team_no,17);
curr_athlete := addParticipant('Lee','Dong-soo','South Korean','Seoul, South Korea',TO_DATE('1974-06-07','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),17,curr_athlete,2);
curr_athlete := addParticipant('Yoo','Yong-sung','South Korean','Dangjin, South Korea',TO_DATE('1974-10-25','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),17,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Doubles Badminton','Indonesia',null,coach_no);
registerTeam(team_no,17);
curr_athlete := addParticipant('Eng','Hian','Indonesian','Surakarta, Indonesia',TO_DATE('1977-05-17','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),17,curr_athlete,3);
curr_athlete := addParticipant('Flandy','Limpele','Indonesian','Manado, Indonesia',TO_DATE('1974-02-09','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),17,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Doubles Badminton','Netherlands',null,coach_no);
registerTeam(team_no,17);
curr_athlete := addParticipant('Jens','Eriksen','Danish','Glostrup, Hovedstaden',TO_DATE('1969-12-30','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),17,curr_athlete,4);
curr_athlete := addParticipant('Martin','Lundgaard Hansen','Danish','Kolding, Denmark',TO_DATE('1972-10-11','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),17,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Doubles Badminton','Indonesia',null,coach_no);
registerTeam(team_no,18);
curr_athlete := addParticipant('Markis','Kido','Indonesian','Jakarta, Indonesia',TO_DATE('1984-08-11','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),18,curr_athlete,1);
curr_athlete := addParticipant('Hendra','Setiawan','Indonesian','Pemalang, Indonesia',TO_DATE('1984-08-25','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),18,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Doubles Badminton','China',null,coach_no);
registerTeam(team_no,18);
curr_athlete := addParticipant('Fu','Haifeng','Chinese','Huilai, Guangdong',TO_DATE('1984-01-02','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),18,curr_athlete,2);
curr_athlete := addParticipant('Cai','Yun','Chinese','Suzhou, China',TO_DATE('1980-01-19','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),18,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Doubles Badminton','South Korea',null,coach_no);
registerTeam(team_no,18);
curr_athlete := addParticipant('Lee','Jae-jin','South Korean','Miryang, South Korea',TO_DATE('1983-01-26','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),18,curr_athlete,3);
curr_athlete := addParticipant('Hwang','Ji-man','South Korean','Miryang, South Korea',TO_DATE('1984-07-08','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),18,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Doubles Badminton','Denmark',null,coach_no);
registerTeam(team_no,18);
curr_athlete := addParticipant('Lars','Paaske','Danish','Horsholm, Denmark',TO_DATE('1976-01-18','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),18,curr_athlete,4);
curr_athlete := addParticipant('Jonas','Rasmussen','Danish','Aarhus, Denmark',TO_DATE('1977-10-28','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),18,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Doubles Badminton','China',null,coach_no);
registerTeam(team_no,19);
curr_athlete := addParticipant('Fu','Haifeng','Chinese','Huilai, Guangdong',TO_DATE('1984-01-02','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),19,curr_athlete,1);
curr_athlete := addParticipant('Cai','Yun','Chinese','Suzhou, China',TO_DATE('1980-01-19','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),19,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Doubles Badminton','Denmark',null,coach_no);
registerTeam(team_no,19);
curr_athlete := addParticipant('Mathias','Boe','Danish','Frederikssund, Denmark',TO_DATE('1980-07-11','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),19,curr_athlete,2);
curr_athlete := addParticipant('Carsten','Mogensen','Danish','Roskilde, Denmark',TO_DATE('1983-07-24','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),19,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Doubles Badminton','South Korea',null,coach_no);
registerTeam(team_no,19);
curr_athlete := addParticipant('Jung','Jae-sung','South Korean','Jeonju, South Korea',TO_DATE('1982-08-25','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),19,curr_athlete,3);
curr_athlete := addParticipant('Lee','Yong-dae','South Korean','Hwasun, South Korea',TO_DATE('1988-09-11','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),19,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Doubles Badminton','Malaysia',null,coach_no);
registerTeam(team_no,19);
curr_athlete := addParticipant('Koo','Kien Keat','Malaysian','Ipoh, Malaysia',TO_DATE('1985-09-18 ','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),19,curr_athlete,4);
curr_athlete := addParticipant('Tan','Boon Heong','Malaysian','Alor Setar, Malaysia',TO_DATE('1987-09-18','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),19,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Doubles Badminton','China',null,coach_no);
registerTeam(team_no,20);
curr_athlete := addParticipant('Fu','Haifeng','Chinese','Huilai, Guangdong',TO_DATE('1984-01-02','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),20,curr_athlete,1);
curr_athlete := addParticipant('Zhang','Nan','Chinese','Beijing, China',TO_DATE('1990-03-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),20,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Doubles Badminton','Malaysia',null,coach_no);
registerTeam(team_no,20);
curr_athlete := addParticipant('Goh','V Shem','Malaysian','Kuala Lumpur, Malaysia',TO_DATE('1989-05-20','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),20,curr_athlete,2);
curr_athlete := addParticipant('Tan','Wee King','Malaysian','Muar, Malaysia',TO_DATE('1989-05-21','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),20,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Doubles Badminton','Great Britain',null,coach_no);
registerTeam(team_no,20);
curr_athlete := addParticipant('Marcus','Ellis','British','Huddersfield, England',TO_DATE('1989-09-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),20,curr_athlete,3);
curr_athlete := addParticipant('Chris','Langridge','British','Epsom, England',TO_DATE('1985-05-02','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),20,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Doubles Badminton','China',null,coach_no);
registerTeam(team_no,20);
curr_athlete := addParticipant('Chai','Biao','Chinese','Hunan, China',TO_DATE('1990-10-10','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),20,curr_athlete,4);
curr_athlete := addParticipant('Hong','Wei','Chinese','Xiamen, China',TO_DATE('1989-10-04','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),20,curr_athlete,4);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Coxless Four Rowing','Great Britain',null,coach_no);
registerTeam(team_no,21);
curr_athlete := addParticipant('Steve','Williams','British','Royal Leamington Spa, United Kingdom',TO_DATE('1976-04-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,1);
curr_athlete := addParticipant('James','Cracknell','British','London, England',TO_DATE('1972-05-05','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,1);
curr_athlete := addParticipant('Edward','Coode','British','Cornwall, England',TO_DATE('1975-06-19','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,1);
curr_athlete := addParticipant('Matthew','Pinsent','British','Norfolk, England',TO_DATE('1970-10-10','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Coxless Four Rowing','Canada',null,coach_no);
registerTeam(team_no,21);
curr_athlete := addParticipant('Cameron','Baerg','Canadian','Saskatoon, Canada',TO_DATE('1972-10-17','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,2);
curr_athlete := addParticipant('Thomas','Herschmiller','Canadian','Comox, Canada',TO_DATE('1978-04-06','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,2);
curr_athlete := addParticipant('Jake','Wetzel','Canadian','Saskatoon, Canada',TO_DATE('1976-12-26','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,2);
curr_athlete := addParticipant('Barney','Williams','Argentinian-Canadian','San Martin de los Andes, Argentina',TO_DATE('1977-03-13','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Coxless Four Rowing','Italy',null,coach_no);
registerTeam(team_no,21);
curr_athlete := addParticipant('Lorenzo','Porzio','Italian','Rome, Italy',TO_DATE('1981-08-24','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,3);
curr_athlete := addParticipant('Dario','Dentale','Italian','Castellamare di Stabia, Italy',TO_DATE('1982-10-26','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,3);
curr_athlete := addParticipant('Luca','Agamennoni','Italian','Livorno, Italy',TO_DATE('1980-08-08','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,3);
curr_athlete := addParticipant('Raffaello','Leonardo','Italian','Naples, Italy',TO_DATE('1973-05-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Coxless Four Rowing','Australia',null,coach_no);
registerTeam(team_no,21);
curr_athlete := addParticipant('David','McGowan','Australian','Perth, Australia',TO_DATE('1981-04-27','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,4);
curr_athlete := addParticipant('Rob','Jahrling','Australian','Burruyacu, Argentina',TO_DATE('1974-02-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,4);
curr_athlete := addParticipant('Tom','Laurich','Australian','unknown, Australia',TO_DATE(' 1980-07-24','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,4);
curr_athlete := addParticipant('David','Dennis','Australian','unknown, Australia',TO_DATE('1980-01-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,4);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Coxless Four Rowing','New Zealand',null,coach_no);
registerTeam(team_no,21);
curr_athlete := addParticipant('Donald','Leach','New Zealander','Christchurch, New Zealand',TO_DATE('1980-11-05','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,5);
curr_athlete := addParticipant('Mahe','Drysdale','New Zealander','Melbourne, Australia',TO_DATE('1978-11-19','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,5);
curr_athlete := addParticipant('Carl','Meyer','New Zealander','Geraldine, New Zealand',TO_DATE('1981-09-03','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,5);
curr_athlete := addParticipant('Eric','Murray','New Zealander','Hastings, New Zealand',TO_DATE('1982-05-06','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,5);
coach_no := createCoach(null,null);
team_no := createTeam('Athens',2004,'Coxless Four Rowing','Poland',null,coach_no);
registerTeam(team_no,21);
curr_athlete := addParticipant('Jaroslaw','Godek','Polish','Szubin, Poland',TO_DATE('1981-01-25','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,6);
curr_athlete := addParticipant('Mariusz','Daniszewski','Polish','Elk, Poland',TO_DATE('1979-01-16','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,6);
curr_athlete := addParticipant('Artur','Rozalski','Polish','Torun, Poland',TO_DATE('1978-03-20','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,6);
curr_athlete := addParticipant('Rafal','Smolinski','Polish','Torun, Poland',TO_DATE('1977-07-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Athens','2004'),21,curr_athlete,6);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Coxless Four Rowing','Great Britain',null,coach_no);
registerTeam(team_no,22);
curr_athlete := addParticipant('Tom','James','British','Cardiff, Wales',TO_DATE('1984-03-11','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,1);
curr_athlete := addParticipant('Steve','Williams','British','Royal Leamington Spa, United Kingdom',TO_DATE('1976-04-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,1);
curr_athlete := addParticipant('Pete','Reed','American-British','Seattle, Washington',TO_DATE('1981-07-27','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,1);
curr_athlete := addParticipant('Andrew','Triggs Hodge','British','Halton, England',TO_DATE('1979-03-03','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Coxless Four Rowing','Australia',null,coach_no);
registerTeam(team_no,22);
curr_athlete := addParticipant('Matt','Ryan','Australian','Sydney, Australia',TO_DATE('1984-06-23','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,2);
curr_athlete := addParticipant('James','Marburgh','Australian','Terang, Australia',TO_DATE('1982-12-27','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,2);
curr_athlete := addParticipant('Cameron','McKenzie-McHarg','Australian','Leongatha, Australia',TO_DATE('1980-04-17','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,2);
curr_athlete := addParticipant('Francis','Hegerty','Australian','unknown, Australia',TO_DATE('1982-09-22','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Coxless Four Rowing','France',null,coach_no);
registerTeam(team_no,22);
curr_athlete := addParticipant('Julien','Despres','French','Clamart, France',TO_DATE('1983-05-12','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,3);
curr_athlete := addParticipant('Benjamin','Rondeau','French','Verdun, France',TO_DATE('1983-10-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,3);
curr_athlete := addParticipant('Germain','Chardin','French','Verdun, France',TO_DATE('1983-05-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,3);
curr_athlete := addParticipant('Dorian','Mortelette','French','Armentieres, France',TO_DATE('1983-11-24','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Coxless Four Rowing','Slovenia',null,coach_no);
registerTeam(team_no,22);
curr_athlete := addParticipant('Tomaz','Pirih','Slovenian','Jesenice, Slovenia',TO_DATE('1981-06-12','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,4);
curr_athlete := addParticipant('Rok','Rozman','Slovenian','Kranj, Slovenia',TO_DATE('1988-01-02','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,4);
curr_athlete := addParticipant('Rok','Kolander','Slovenian','Maribor, Slovenia',TO_DATE('1980-02-08','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,4);
curr_athlete := addParticipant('Miha','Pirih','Slovenian','Jesenice, Slovenia',TO_DATE('1978-03-10','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,4);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Coxless Four Rowing','Czech Republic',null,coach_no);
registerTeam(team_no,22);
curr_athlete := addParticipant('Jan','Gruber','Czech','Prague, Czech Republic',TO_DATE('1984-03-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,5);
curr_athlete := addParticipant('Michal','Horvath','Czech','Prague, Czech Republic',TO_DATE('1987-06-30','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,5);
curr_athlete := addParticipant('Milan','Bruncvik','Czech','Litomerice, Czech Republic',TO_DATE('1984-06-21','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,5);
curr_athlete := addParticipant('Karel','Neffe','Czech','Prague, Czech Republic',TO_DATE('1985-02-21','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,5);
coach_no := createCoach(null,null);
team_no := createTeam('Beijing',2008,'Coxless Four Rowing','Germany',null,coach_no);
registerTeam(team_no,22);
curr_athlete := addParticipant('Jochen','Urban','German','Krefeld, Germany',TO_DATE('1983-09-23','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,6);
curr_athlete := addParticipant('Richard','Schmidt','German','Trier, Germany',TO_DATE('1987-05-23','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,6);
curr_athlete := addParticipant('Urs','Kaufer','German','Neu-Ulm, Bavaria',TO_DATE('1984-11-17','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,6);
curr_athlete := addParticipant('Gregor','Hauffe','German','Magdeburg, Germany',TO_DATE('1982-05-20','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Beijing','2008'),22,curr_athlete,6);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Coxless Four Rowing','Great Britain',null,coach_no);
registerTeam(team_no,23);
curr_athlete := addParticipant('Alex','Gregory','British','Cheltenham, England',TO_DATE('1984-03-11','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,1);
curr_athlete := addParticipant('Tom','James','British','Cardiff, Wales',TO_DATE('1984-03-11','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,1);
curr_athlete := addParticipant('Pete','Reed','American-British','Seattle, Washington',TO_DATE('1981-07-27','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,1);
curr_athlete := addParticipant('Andrew','Triggs Hodge','British','Halton, England',TO_DATE('1979-03-03','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Coxless Four Rowing','Australia',null,coach_no);
registerTeam(team_no,23);
curr_athlete := addParticipant('James','Chapman','Australian','Sydney, Australia',TO_DATE('1979-11-22','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,2);
curr_athlete := addParticipant('Josh','Dunkley-Smith','Australian','Melbourne, Australia',TO_DATE('1989-06-28','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,2);
curr_athlete := addParticipant('Drew','Ginn','Australian','unknown, Australia',TO_DATE('1974-11-20','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,2);
curr_athlete := addParticipant('Will','Lockwood','Australian','Fitzroy, Australia',TO_DATE('1988-05-13','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Coxless Four Rowing','United States',null,coach_no);
registerTeam(team_no,23);
curr_athlete := addParticipant('Charlie','Cole','American','New York City, New York',TO_DATE('1986-06-21','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,3);
curr_athlete := addParticipant('Scott','Gault','American','Berkeley, California',TO_DATE('1983-01-31','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,3);
curr_athlete := addParticipant('Glenn','Ochal','American','Philadelphia, Pennsylvania',TO_DATE('1986-03-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,3);
curr_athlete := addParticipant('Henrik','Rummel','Danish-American','Copenhagen, Denmark',TO_DATE('1987-09-26','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Coxless Four Rowing','Greece',null,coach_no);
registerTeam(team_no,23);
curr_athlete := addParticipant('Ioannis','Christou','Greek','Kastoria, Greece',TO_DATE('1983-06-23','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,4);
curr_athlete := addParticipant('Stergios','Papachristos','Greek','Volos, Greece',TO_DATE('1989-01-26','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,4);
curr_athlete := addParticipant('Ioannis','Tsilis','Greek','Ioannina, Greece',TO_DATE('1986-07-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,4);
curr_athlete := addParticipant('Georgios','Tziallas','Greek','Ioannina, Greece',TO_DATE('1987-07-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,4);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Coxless Four Rowing','Netherlands',null,coach_no);
registerTeam(team_no,23);
curr_athlete := addParticipant('Kaj','Hendriks','Dutch','Wageningen, Netherlands',TO_DATE('1987-08-19','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,5);
curr_athlete := addParticipant('Ruben','Knab','Dutch','Ede, Netherlands',TO_DATE('1988-02-19','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,5);
curr_athlete := addParticipant('Boaz','Meylink','Dutch','Deventer, Netherlands',TO_DATE('1984-03-22','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,5);
curr_athlete := addParticipant('Mechiel','Versluis','Dutch','Ooststellingwerf, Netherlands',TO_DATE('1987-07-29','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,5);
coach_no := createCoach(null,null);
team_no := createTeam('London',2012,'Coxless Four Rowing','Germany',null,coach_no);
registerTeam(team_no,23);
curr_athlete := addParticipant('Urs','Kaufer','German','Neu-Ulm, Bavaria',TO_DATE('1984-11-17','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,6);
curr_athlete := addParticipant('Gregor','Hauffe','German','Magdeburg, Germany',TO_DATE('1982-05-20','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,6);
curr_athlete := addParticipant('Sebastian','Schmidt','German','Wiesbaden, Germany',TO_DATE('1985-01-06','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,6);
curr_athlete := addParticipant('Toni','Seifert','German','Dresden, Germany',TO_DATE('1981-04-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('London','2012'),23,curr_athlete,6);
end;
declare
   coach_no integer;
   team_no integer;
   curr_athlete integer;
begin
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Coxless Four Rowing','Great Britain',null,coach_no);
registerTeam(team_no,24);
curr_athlete := addParticipant('Alex','Gregory','British','Cheltenham, England',TO_DATE('1984-03-11','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,1);
curr_athlete := addParticipant('Moe','Sbihi','British','Kingston upon Thames, England',TO_DATE('1988-03-27','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,1);
curr_athlete := addParticipant('George','Nash','British','Guildford, England',TO_DATE('1989-10-02','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,1);
curr_athlete := addParticipant('Constantine','Louloudis','British','London, England',TO_DATE('1991-09-15','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,1);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Coxless Four Rowing','Australia',null,coach_no);
registerTeam(team_no,24);
curr_athlete := addParticipant('Will','Lockwood','Australian','Fitzroy, Australia',TO_DATE('1988-05-13','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,2);
curr_athlete := addParticipant('Josh','Dunkley-Smith','Australian','Melbourne, Australia',TO_DATE('1989-06-28','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,2);
curr_athlete := addParticipant('Josh','Booth','Australian','Melbourne, Australia',TO_DATE('1990-10-09','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,2);
curr_athlete := addParticipant('Alexander','Hill','Australian','Berri, Australia',TO_DATE('1993-03-11','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,2);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Coxless Four Rowing','Italy',null,coach_no);
registerTeam(team_no,24);
curr_athlete := addParticipant('Domenico','Montrone','Italian','unknown, Italy',TO_DATE('1986-05-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,3);
curr_athlete := addParticipant('Matteo','Castaldo','Italian','Naples, Italy',TO_DATE('1985-12-11','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,3);
curr_athlete := addParticipant('Matteo','Lodo','Italian','Terracina, Italy',TO_DATE('1994-10-25','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,3);
curr_athlete := addParticipant('Giuseppe','Vicino','Italian','Naples, Italy',TO_DATE('1993-02-26','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,3);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Coxless Four Rowing','South Africa',null,coach_no);
registerTeam(team_no,24);
curr_athlete := addParticipant('David','Hunt','South African','unknown, South Africa',TO_DATE('1991-02-01','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,4);
curr_athlete := addParticipant('Jonty','Smith','South African','unknown, South Africa',TO_DATE('1992-02-19','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,4);
curr_athlete := addParticipant('Vincent','Breet','South African','unknown, South Africa',TO_DATE('1993-04-26','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,4);
curr_athlete := addParticipant('Jake','Green','South African','unknown, South Africa',TO_DATE('1994-03-30','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,4);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Coxless Four Rowing','Netherlands',null,coach_no);
registerTeam(team_no,24);
curr_athlete := addParticipant('Harold','Langen','Dutch','unknown, Netherlands',TO_DATE('1986-10-27','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,5);
curr_athlete := addParticipant('Peter','van Schie','Dutch','unknown, Netherlands',TO_DATE('1988-03-03','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,5);
curr_athlete := addParticipant('Vincent','vand der Want','Dutch','unknown, Netherlands',TO_DATE('1985-10-21','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,5);
curr_athlete := addParticipant('Govert','Viergever','Dutch','unknown, Netherlands',TO_DATE('1989-07-29','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,5);
coach_no := createCoach(null,null);
team_no := createTeam('Rio',2016,'Coxless Four Rowing','Canada',null,coach_no);
registerTeam(team_no,24);
curr_athlete := addParticipant('Will','Crothers','Canadian','Kingston, Ontario',TO_DATE('1987-06-14','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,6);
curr_athlete := addParticipant('Tim','Schrijver','Canadian','Strathroy-Caradoc, Ontario',TO_DATE('1992-02-07','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,6);
curr_athlete := addParticipant('Conlin','McCabe','Canadian','Brockville, Ontario',TO_DATE('1990-08-20','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,6);
curr_athlete := addParticipant('Kai','Langerfeld','Canadian','North Vancouver, British Columbia',TO_DATE('1987-07-05','yyyy-mm-dd'));
addTeamMember(team_no,curr_athlete);
addDefaultEventOutcome(getOlympics('Rio','2016'),24,curr_athlete,6);
end;
commit;